In [63]:
# https://medium.com/@niveditha.itengineer/learn-how-to-setup-portaudio-and-pyaudio-in-ubuntu-to-play-with-speech-recognition-8d2fff660e94

import sounddevice as sd
import numpy as np
import scipy.signal
from scipy.special import softmax
import timeit
import python_speech_features
import os
import json
#import RPi.GPIO as GPIO
from kws_streaming.data import input_data
from datetime import datetime


#from tflite_runtime.interpreter import Interpreter
import tensorflow as tf


In [64]:
# Parameters
#debug_time = 1
#debug_acc = 0
#led_pin = 8
word_threshold = 0.9

sample_rate = 16000

num_channels = 1
model_path = 'models3_30k/svdf/tflite_stream_state_external/stream_state_external.tflite'


# GPIO 
#GPIO.setwarnings(False)
#GPIO.setmode(GPIO.BOARD)
#GPIO.setup(8, GPIO.OUT, initial=GPIO.LOW)

current_dir = os.getcwd()
DATA_PATH = os.path.join(current_dir, "data2/")
MODELS_PATH = current_dir

file_name='models3_30k'
train_dir = os.path.join(MODELS_PATH, file_name, 'svdf')

current_dir

'/mnt/disk0shared/bdjola/Documents/Technique/DevML/kws_streaming2/kws_streaming'

In [65]:
# below is another way of reading flags - through json
with tf.compat.v1.gfile.Open(os.path.join(train_dir, 'flags.json'), 'r') as fd:
   flags_json = json.load(fd)

class DictStruct(object):
   def __init__(self, **entries):
     self.__dict__.update(entries)

flags = DictStruct(**flags_json)

In [66]:
# prepare mapping of index to word
audio_processor = input_data.AudioProcessor(flags)
index_to_label = {}
# labels used for training
for word in audio_processor.word_to_index.keys():
  if audio_processor.word_to_index[word] == data.input_data.SILENCE_INDEX:
    index_to_label[audio_processor.word_to_index[word]] = data.input_data.SILENCE_LABEL
  elif audio_processor.word_to_index[word] == data.input_data.UNKNOWN_WORD_INDEX:
    index_to_label[audio_processor.word_to_index[word]] = data.input_data.UNKNOWN_WORD_LABEL
  else:
    index_to_label[audio_processor.word_to_index[word]] = word

# training labels
index_to_label

2024-02-25 19:27:54.042517: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-02-25 19:27:54.042548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-02-25 19:27:54.042552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      


{10: 'follow',
 11: 'forward',
 16: 'learn',
 2: 'backward',
 3: 'bed',
 26: 'sheila',
 5: 'cat',
 4: 'bird',
 14: 'happy',
 15: 'house',
 18: 'marvin',
 6: 'dog',
 30: 'tree',
 12: 'four',
 21: 'off',
 33: 'visual',
 24: 'right',
 8: 'eight',
 17: 'left',
 22: 'on',
 13: 'go',
 23: 'one',
 19: 'nine',
 7: 'down',
 25: 'seven',
 9: 'five',
 34: 'wow',
 29: 'three',
 32: 'up',
 20: 'no',
 28: 'stop',
 31: 'two',
 27: 'six',
 35: 'yes',
 36: 'zero',
 0: '_silence_'}

In [67]:
# Load model (interpreter)
#interpreter = Interpreter(model_path)
interpreter = tf.lite.Interpreter(model_path)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)

[{'name': 'input_audio', 'index': 0, 'shape': array([  1, 320], dtype=int32), 'shape_signature': array([  1, 320], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'streaming/speech_features/data_frame_1input_state', 'index': 1, 'shape': array([  1, 640], dtype=int32), 'shape_signature': array([  1, 640], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'streaming/svdf_0/depthwise_conv1d_6/depthwise_conv1d_6input_state', 'index': 2, 'shape': array([ 1,  4, 16], dtype=int32), 'shape_signature': array([ 1,  4, 16], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameter

In [68]:
inputs = []
for s in range(len(input_details)):
  inputs.append(np.zeros(input_details[s]['shape'], dtype=np.float32))

input_details[0]['shape']

array([  1, 320], dtype=int32)

In [69]:
# Decimate (filter and downsample)
def decimate(signal, old_fs, new_fs):
    
    # Check to make sure we're downsampling
    if new_fs > old_fs:
        print("Error: target sample rate higher than original")
        return signal, old_fs
    
    # We can only downsample by an integer factor
    dec_factor = old_fs / new_fs
    if not dec_factor.is_integer():
        print("Error: can only decimate by integer factor")
        return signal, old_fs

    # Do decimation
    resampled_signal = scipy.signal.decimate(signal, int(dec_factor))

    return resampled_signal, new_fs

In [70]:
# This gets called every 0.5 seconds
def sd_callback(rec, frames, time, status):   
    #print('rec:', rec.shape) 
    # Remove 2nd dimension from recording sample
    #rec = np.squeeze(rec)
    rec = np.reshape(rec, (1,-1))

    # set input audio data (by default input data at index 0)
    interpreter.set_tensor(input_details[0]['index'], rec)

    # set input states (index 1...)
    for s in range(1, len(input_details)):
        interpreter.set_tensor(input_details[s]['index'], inputs[s])

    # run inference
    interpreter.invoke()

    # get output: classification
    out_tflite = interpreter.get_tensor(output_details[0]['index'])
    #print(start / 16000.0, np.argmax(out_tflite), np.max(out_tflite))

    # get output states and set it back to input states
    # which will be fed in the next inference cycle
    for s in range(1, len(input_details)):
    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
        inputs[s] = interpreter.get_tensor(output_details[s]['index'])

    out_tflite_argmax = np.argmax(out_tflite)

    probas = softmax(out_tflite)
    proba = np.max(probas)
    if (out_tflite_argmax>1) and (proba > word_threshold):
        print(datetime.now().strftime("%d/%m/%Y %H:%M:%S"), index_to_label[out_tflite_argmax], proba)


  

    


In [71]:
reset_state = True

# before processing new test sequence we can reset model state
# if we reset model state then it is not real streaming mode
if reset_state:
  for s in range(len(input_details)):
    print(input_details[s]['shape'])
    inputs[s] = np.zeros(input_details[s]['shape'], dtype=np.float32)

[  1 320]
[  1 640]
[ 1  4 16]
[ 1 10 32]
[ 1 10 32]
[ 1 10 32]
[ 1 10 64]
[  1  10 128]
[  1   1 128]


In [72]:
# Start streaming from microphone
print('channels:',num_channels, 'samplerate:',sample_rate, 'blocksize:', flags.window_stride_samples)
with sd.InputStream(channels=num_channels,
                    samplerate=sample_rate,
                    blocksize=flags.window_stride_samples,
                    callback=sd_callback):
    while True:
        pass

channels: 1 samplerate: 16000 blocksize: 320


25/02/2024 19:28:03 down 0.91993946
25/02/2024 19:28:03 down 0.9251196
25/02/2024 19:28:03 down 0.9666034
25/02/2024 19:28:04 down 0.9408224
25/02/2024 19:28:04 down 0.9421001
25/02/2024 19:28:04 down 0.9352198
25/02/2024 19:28:04 down 0.95961094
25/02/2024 19:28:04 down 0.9514797
25/02/2024 19:28:04 down 0.90947855
25/02/2024 19:28:09 left 0.9186406
25/02/2024 19:28:09 left 0.9639121
25/02/2024 19:28:09 left 0.96420586
25/02/2024 19:28:09 left 0.97195643
25/02/2024 19:28:09 left 0.979404
25/02/2024 19:28:09 left 0.9890932
25/02/2024 19:28:09 left 0.9898051
25/02/2024 19:28:09 left 0.97883993
25/02/2024 19:28:09 left 0.95849186
25/02/2024 19:28:09 left 0.9597308
25/02/2024 19:28:09 left 0.95508987
25/02/2024 19:28:09 left 0.9640464
25/02/2024 19:28:09 left 0.981849
25/02/2024 19:28:09 left 0.9941454
25/02/2024 19:28:09 left 0.9925193
25/02/2024 19:28:10 left 0.9864532
25/02/2024 19:28:10 left 0.9806746
25/02/2024 19:28:10 left 0.9644736
25/02/2024 19:28:10 left 0.93438494
25/02/2024 19

KeyboardInterrupt: 